manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rianadon
      url-base: https://github.com/rianadon
  projects:
    - name: zmk
      remote: rianadon
      revision: main
      import: app/west.yml
  self:
    path: config
    import: deps.yml
